/* tslint:disable */
/* eslint-disable */
/**
 * Finance Tracker API
 * Read-only REST API that surfaces financial data collected by the CLI ingestion tool. All writes are performed exclusively by the CLI.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AccountRead } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * AccountsApi - axios parameter creator
 */
export const AccountsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Return transaction history for a specific account.  TODO: Implement in AccountService.
         * @summary Account Transactions
         * @param {string} accountId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountTransactionsApiV1AccountsAccountIdTransactionsGet: async (accountId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('accountTransactionsApiV1AccountsAccountIdTransactionsGet', 'accountId', accountId)
            const localVarPath = `/api/v1/accounts/{account_id}/transactions`
                .replace(`{${"account_id"}}`, encodeURIComponent(String(accountId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return all known accounts/cards/wallets.  TODO: Implement in AccountService.
         * @summary List Accounts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAccountsApiV1AccountsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/accounts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AccountsApi - functional programming interface
 */
export const AccountsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AccountsApiAxiosParamCreator(configuration)
    return {
        /**
         * Return transaction history for a specific account.  TODO: Implement in AccountService.
         * @summary Account Transactions
         * @param {string} accountId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountTransactionsApiV1AccountsAccountIdTransactionsGet(accountId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountTransactionsApiV1AccountsAccountIdTransactionsGet(accountId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountsApi.accountTransactionsApiV1AccountsAccountIdTransactionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return all known accounts/cards/wallets.  TODO: Implement in AccountService.
         * @summary List Accounts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAccountsApiV1AccountsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AccountRead>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listAccountsApiV1AccountsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountsApi.listAccountsApiV1AccountsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AccountsApi - factory interface
 */
export const AccountsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AccountsApiFp(configuration)
    return {
        /**
         * Return transaction history for a specific account.  TODO: Implement in AccountService.
         * @summary Account Transactions
         * @param {string} accountId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountTransactionsApiV1AccountsAccountIdTransactionsGet(accountId: string, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.accountTransactionsApiV1AccountsAccountIdTransactionsGet(accountId, options).then((request) => request(axios, basePath));
        },
        /**
         * Return all known accounts/cards/wallets.  TODO: Implement in AccountService.
         * @summary List Accounts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAccountsApiV1AccountsGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<AccountRead>> {
            return localVarFp.listAccountsApiV1AccountsGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AccountsApi - object-oriented interface
 */
export class AccountsApi extends BaseAPI {
    /**
     * Return transaction history for a specific account.  TODO: Implement in AccountService.
     * @summary Account Transactions
     * @param {string} accountId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public accountTransactionsApiV1AccountsAccountIdTransactionsGet(accountId: string, options?: RawAxiosRequestConfig) {
        return AccountsApiFp(this.configuration).accountTransactionsApiV1AccountsAccountIdTransactionsGet(accountId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return all known accounts/cards/wallets.  TODO: Implement in AccountService.
     * @summary List Accounts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listAccountsApiV1AccountsGet(options?: RawAxiosRequestConfig) {
        return AccountsApiFp(this.configuration).listAccountsApiV1AccountsGet(options).then((request) => request(this.axios, this.basePath));
    }
}

