/* tslint:disable */
/* eslint-disable */
/**
 * Finance Tracker API
 * Read-only REST API that surfaces financial data collected by the CLI ingestion tool. All writes are performed exclusively by the CLI.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CashflowPoint } from '../models';
// @ts-ignore
import type { CategoryBreakdown } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { MerchantSummary } from '../models';
/**
 * AnalyticsApi - axios parameter creator
 */
export const AnalyticsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Highlight transactions significantly above usual category amounts.  TODO: Implement in AnalyticsService.
         * @summary Anomaly Highlights
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        anomalyHighlightsApiV1AnalyticsAnomaliesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/analytics/anomalies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Monthly income vs expense for the past N months.  TODO: Implement in AnalyticsService.
         * @summary Cashflow
         * @param {number} [months] Number of months to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashflowApiV1AnalyticsCashflowGet: async (months?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/analytics/cashflow`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (months !== undefined) {
                localVarQueryParameter['months'] = months;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Spending by category.  TODO: Implement in AnalyticsService.
         * @summary Category Breakdown
         * @param {string | null} [month] Filter to a specific month (YYYY-MM)
         * @param {string | null} [dateFrom] 
         * @param {string | null} [dateTo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoryBreakdownApiV1AnalyticsCategoryBreakdownGet: async (month?: string | null, dateFrom?: string | null, dateTo?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/analytics/category-breakdown`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (month !== undefined) {
                localVarQueryParameter['month'] = month;
            }

            if (dateFrom !== undefined) {
                localVarQueryParameter['date_from'] = dateFrom;
            }

            if (dateTo !== undefined) {
                localVarQueryParameter['date_to'] = dateTo;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Detect recurring transactions by pattern.  TODO: Implement in AnalyticsService.
         * @summary Recurring Transactions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recurringTransactionsApiV1AnalyticsRecurringGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/analytics/recurring`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Top merchants by total spend.  TODO: Implement in AnalyticsService.
         * @summary Top Merchants
         * @param {string | null} [month] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        topMerchantsApiV1AnalyticsTopMerchantsGet: async (month?: string | null, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/analytics/top-merchants`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (month !== undefined) {
                localVarQueryParameter['month'] = month;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AnalyticsApi - functional programming interface
 */
export const AnalyticsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AnalyticsApiAxiosParamCreator(configuration)
    return {
        /**
         * Highlight transactions significantly above usual category amounts.  TODO: Implement in AnalyticsService.
         * @summary Anomaly Highlights
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async anomalyHighlightsApiV1AnalyticsAnomaliesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.anomalyHighlightsApiV1AnalyticsAnomaliesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.anomalyHighlightsApiV1AnalyticsAnomaliesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Monthly income vs expense for the past N months.  TODO: Implement in AnalyticsService.
         * @summary Cashflow
         * @param {number} [months] Number of months to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cashflowApiV1AnalyticsCashflowGet(months?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CashflowPoint>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cashflowApiV1AnalyticsCashflowGet(months, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.cashflowApiV1AnalyticsCashflowGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Spending by category.  TODO: Implement in AnalyticsService.
         * @summary Category Breakdown
         * @param {string | null} [month] Filter to a specific month (YYYY-MM)
         * @param {string | null} [dateFrom] 
         * @param {string | null} [dateTo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoryBreakdownApiV1AnalyticsCategoryBreakdownGet(month?: string | null, dateFrom?: string | null, dateTo?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CategoryBreakdown>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoryBreakdownApiV1AnalyticsCategoryBreakdownGet(month, dateFrom, dateTo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.categoryBreakdownApiV1AnalyticsCategoryBreakdownGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Detect recurring transactions by pattern.  TODO: Implement in AnalyticsService.
         * @summary Recurring Transactions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recurringTransactionsApiV1AnalyticsRecurringGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recurringTransactionsApiV1AnalyticsRecurringGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.recurringTransactionsApiV1AnalyticsRecurringGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Top merchants by total spend.  TODO: Implement in AnalyticsService.
         * @summary Top Merchants
         * @param {string | null} [month] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async topMerchantsApiV1AnalyticsTopMerchantsGet(month?: string | null, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MerchantSummary>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.topMerchantsApiV1AnalyticsTopMerchantsGet(month, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AnalyticsApi.topMerchantsApiV1AnalyticsTopMerchantsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AnalyticsApi - factory interface
 */
export const AnalyticsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AnalyticsApiFp(configuration)
    return {
        /**
         * Highlight transactions significantly above usual category amounts.  TODO: Implement in AnalyticsService.
         * @summary Anomaly Highlights
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        anomalyHighlightsApiV1AnalyticsAnomaliesGet(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.anomalyHighlightsApiV1AnalyticsAnomaliesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Monthly income vs expense for the past N months.  TODO: Implement in AnalyticsService.
         * @summary Cashflow
         * @param {number} [months] Number of months to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cashflowApiV1AnalyticsCashflowGet(months?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<CashflowPoint>> {
            return localVarFp.cashflowApiV1AnalyticsCashflowGet(months, options).then((request) => request(axios, basePath));
        },
        /**
         * Spending by category.  TODO: Implement in AnalyticsService.
         * @summary Category Breakdown
         * @param {string | null} [month] Filter to a specific month (YYYY-MM)
         * @param {string | null} [dateFrom] 
         * @param {string | null} [dateTo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoryBreakdownApiV1AnalyticsCategoryBreakdownGet(month?: string | null, dateFrom?: string | null, dateTo?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<Array<CategoryBreakdown>> {
            return localVarFp.categoryBreakdownApiV1AnalyticsCategoryBreakdownGet(month, dateFrom, dateTo, options).then((request) => request(axios, basePath));
        },
        /**
         * Detect recurring transactions by pattern.  TODO: Implement in AnalyticsService.
         * @summary Recurring Transactions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recurringTransactionsApiV1AnalyticsRecurringGet(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.recurringTransactionsApiV1AnalyticsRecurringGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Top merchants by total spend.  TODO: Implement in AnalyticsService.
         * @summary Top Merchants
         * @param {string | null} [month] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        topMerchantsApiV1AnalyticsTopMerchantsGet(month?: string | null, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<MerchantSummary>> {
            return localVarFp.topMerchantsApiV1AnalyticsTopMerchantsGet(month, limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AnalyticsApi - object-oriented interface
 */
export class AnalyticsApi extends BaseAPI {
    /**
     * Highlight transactions significantly above usual category amounts.  TODO: Implement in AnalyticsService.
     * @summary Anomaly Highlights
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public anomalyHighlightsApiV1AnalyticsAnomaliesGet(options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).anomalyHighlightsApiV1AnalyticsAnomaliesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Monthly income vs expense for the past N months.  TODO: Implement in AnalyticsService.
     * @summary Cashflow
     * @param {number} [months] Number of months to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cashflowApiV1AnalyticsCashflowGet(months?: number, options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).cashflowApiV1AnalyticsCashflowGet(months, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Spending by category.  TODO: Implement in AnalyticsService.
     * @summary Category Breakdown
     * @param {string | null} [month] Filter to a specific month (YYYY-MM)
     * @param {string | null} [dateFrom] 
     * @param {string | null} [dateTo] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public categoryBreakdownApiV1AnalyticsCategoryBreakdownGet(month?: string | null, dateFrom?: string | null, dateTo?: string | null, options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).categoryBreakdownApiV1AnalyticsCategoryBreakdownGet(month, dateFrom, dateTo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Detect recurring transactions by pattern.  TODO: Implement in AnalyticsService.
     * @summary Recurring Transactions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public recurringTransactionsApiV1AnalyticsRecurringGet(options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).recurringTransactionsApiV1AnalyticsRecurringGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Top merchants by total spend.  TODO: Implement in AnalyticsService.
     * @summary Top Merchants
     * @param {string | null} [month] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public topMerchantsApiV1AnalyticsTopMerchantsGet(month?: string | null, limit?: number, options?: RawAxiosRequestConfig) {
        return AnalyticsApiFp(this.configuration).topMerchantsApiV1AnalyticsTopMerchantsGet(month, limit, options).then((request) => request(this.axios, this.basePath));
    }
}

