/* tslint:disable */
/* eslint-disable */
/**
 * Finance Tracker API
 * Read-only REST API that surfaces financial data collected by the CLI ingestion tool. All writes are performed exclusively by the CLI.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { MonthlyStats } from '../models';
/**
 * StatsApi - axios parameter creator
 */
export const StatsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Return total debits, total credits, and net cashflow for a given month.  TODO: Implement in StatsService.
         * @summary Monthly Stats
         * @param {string | null} [month] Month in YYYY-MM format (default: current month)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        monthlyStatsApiV1StatsGet: async (month?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (month !== undefined) {
                localVarQueryParameter['month'] = month;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StatsApi - functional programming interface
 */
export const StatsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StatsApiAxiosParamCreator(configuration)
    return {
        /**
         * Return total debits, total credits, and net cashflow for a given month.  TODO: Implement in StatsService.
         * @summary Monthly Stats
         * @param {string | null} [month] Month in YYYY-MM format (default: current month)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async monthlyStatsApiV1StatsGet(month?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MonthlyStats>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.monthlyStatsApiV1StatsGet(month, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatsApi.monthlyStatsApiV1StatsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StatsApi - factory interface
 */
export const StatsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StatsApiFp(configuration)
    return {
        /**
         * Return total debits, total credits, and net cashflow for a given month.  TODO: Implement in StatsService.
         * @summary Monthly Stats
         * @param {string | null} [month] Month in YYYY-MM format (default: current month)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        monthlyStatsApiV1StatsGet(month?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<MonthlyStats> {
            return localVarFp.monthlyStatsApiV1StatsGet(month, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StatsApi - object-oriented interface
 */
export class StatsApi extends BaseAPI {
    /**
     * Return total debits, total credits, and net cashflow for a given month.  TODO: Implement in StatsService.
     * @summary Monthly Stats
     * @param {string | null} [month] Month in YYYY-MM format (default: current month)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public monthlyStatsApiV1StatsGet(month?: string | null, options?: RawAxiosRequestConfig) {
        return StatsApiFp(this.configuration).monthlyStatsApiV1StatsGet(month, options).then((request) => request(this.axios, this.basePath));
    }
}

