/* tslint:disable */
/* eslint-disable */
/**
 * Finance Tracker API
 * Read-only REST API that surfaces financial data collected by the CLI ingestion tool. All writes are performed exclusively by the CLI.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Direction } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { TransactionListResponse } from '../models';
/**
 * TransactionsApi - axios parameter creator
 */
export const TransactionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List Transactions
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {string | null} [accountId] 
         * @param {string | null} [provider] 
         * @param {string | null} [category] 
         * @param {Direction | null} [direction] 
         * @param {string | null} [dateFrom] ISO date YYYY-MM-DD
         * @param {string | null} [dateTo] ISO date YYYY-MM-DD
         * @param {string | null} [search] Search by merchant or payee
         * @param {string} [sortBy] 
         * @param {string} [sortOrder] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTransactionsApiV1TransactionsGet: async (page?: number, pageSize?: number, accountId?: string | null, provider?: string | null, category?: string | null, direction?: Direction | null, dateFrom?: string | null, dateTo?: string | null, search?: string | null, sortBy?: string, sortOrder?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (accountId !== undefined) {
                localVarQueryParameter['account_id'] = accountId;
            }

            if (provider !== undefined) {
                localVarQueryParameter['provider'] = provider;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (direction !== undefined) {
                localVarQueryParameter['direction'] = direction;
            }

            if (dateFrom !== undefined) {
                localVarQueryParameter['date_from'] = (dateFrom as any instanceof Date) ?
                    (dateFrom as any).toISOString().substring(0,10) :
                    dateFrom;
            }

            if (dateTo !== undefined) {
                localVarQueryParameter['date_to'] = (dateTo as any instanceof Date) ?
                    (dateTo as any).toISOString().substring(0,10) :
                    dateTo;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sort_by'] = sortBy;
            }

            if (sortOrder !== undefined) {
                localVarQueryParameter['sort_order'] = sortOrder;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransactionsApi - functional programming interface
 */
export const TransactionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TransactionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List Transactions
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {string | null} [accountId] 
         * @param {string | null} [provider] 
         * @param {string | null} [category] 
         * @param {Direction | null} [direction] 
         * @param {string | null} [dateFrom] ISO date YYYY-MM-DD
         * @param {string | null} [dateTo] ISO date YYYY-MM-DD
         * @param {string | null} [search] Search by merchant or payee
         * @param {string} [sortBy] 
         * @param {string} [sortOrder] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTransactionsApiV1TransactionsGet(page?: number, pageSize?: number, accountId?: string | null, provider?: string | null, category?: string | null, direction?: Direction | null, dateFrom?: string | null, dateTo?: string | null, search?: string | null, sortBy?: string, sortOrder?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTransactionsApiV1TransactionsGet(page, pageSize, accountId, provider, category, direction, dateFrom, dateTo, search, sortBy, sortOrder, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.listTransactionsApiV1TransactionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TransactionsApi - factory interface
 */
export const TransactionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TransactionsApiFp(configuration)
    return {
        /**
         * 
         * @summary List Transactions
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {string | null} [accountId] 
         * @param {string | null} [provider] 
         * @param {string | null} [category] 
         * @param {Direction | null} [direction] 
         * @param {string | null} [dateFrom] ISO date YYYY-MM-DD
         * @param {string | null} [dateTo] ISO date YYYY-MM-DD
         * @param {string | null} [search] Search by merchant or payee
         * @param {string} [sortBy] 
         * @param {string} [sortOrder] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTransactionsApiV1TransactionsGet(page?: number, pageSize?: number, accountId?: string | null, provider?: string | null, category?: string | null, direction?: Direction | null, dateFrom?: string | null, dateTo?: string | null, search?: string | null, sortBy?: string, sortOrder?: string, options?: RawAxiosRequestConfig): AxiosPromise<TransactionListResponse> {
            return localVarFp.listTransactionsApiV1TransactionsGet(page, pageSize, accountId, provider, category, direction, dateFrom, dateTo, search, sortBy, sortOrder, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TransactionsApi - object-oriented interface
 */
export class TransactionsApi extends BaseAPI {
    /**
     * 
     * @summary List Transactions
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {string | null} [accountId] 
     * @param {string | null} [provider] 
     * @param {string | null} [category] 
     * @param {Direction | null} [direction] 
     * @param {string | null} [dateFrom] ISO date YYYY-MM-DD
     * @param {string | null} [dateTo] ISO date YYYY-MM-DD
     * @param {string | null} [search] Search by merchant or payee
     * @param {string} [sortBy] 
     * @param {string} [sortOrder] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listTransactionsApiV1TransactionsGet(page?: number, pageSize?: number, accountId?: string | null, provider?: string | null, category?: string | null, direction?: Direction | null, dateFrom?: string | null, dateTo?: string | null, search?: string | null, sortBy?: string, sortOrder?: string, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).listTransactionsApiV1TransactionsGet(page, pageSize, accountId, provider, category, direction, dateFrom, dateTo, search, sortBy, sortOrder, options).then((request) => request(this.axios, this.basePath));
    }
}

