/* tslint:disable */
/* eslint-disable */
/**
 * Finance Tracker API
 * Read-only REST API that surfaces financial data collected by the CLI ingestion tool. All writes are performed exclusively by the CLI.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Raw cached email row (provider message id in ``mail_id``).
 */
export interface FetchedEmailRead {
    'body_text': string;
    'created_at': string;
    'id': number;
    'internal_date_ms': number;
    'mail_id': string;
    'sender'?: string | null;
    'snippet'?: string | null;
    'subject'?: string | null;
    'thread_id'?: string | null;
}

