/* tslint:disable */
/* eslint-disable */
/**
 * Finance Tracker API
 * Read-only REST API that surfaces financial data collected by the CLI ingestion tool. All writes are performed exclusively by the CLI.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Classification/parser state for one cached email (1:1 with ``fetched_emails.id``).
 */
export interface FetchedEmailEnrichmentRead {
    'classification'?: string | null;
    'classification_id'?: number | null;
    'classification_reason'?: string | null;
    'created_at': string;
    'fetched_email_id': number;
    'parser_id'?: number | null;
    'updated_at': string;
}

