/* tslint:disable */
/* eslint-disable */
/**
 * Finance Tracker API
 * Read-only REST API that surfaces financial data collected by the CLI ingestion tool. All writes are performed exclusively by the CLI.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Direction } from './direction';

/**
 * Full transaction response including DB-assigned ``id`` and audit fields.
 */
export interface TransactionRead {
    'account_id'?: string | null;
    'account_type'?: string | null;
    'amount'?: string | null;
    'amount_parsed': number;
    'category'?: string | null;
    'created_at': string;
    'currency'?: string;
    'direction': Direction;
    'id': number;
    'mail_id': string;
    'merchant'?: string | null;
    'provider'?: string | null;
    'status'?: string | null;
    'sub_type'?: string | null;
    'transacted_at': string;
    'transaction_type'?: string | null;
    'txn_id'?: string | null;
}



