/* tslint:disable */
/* eslint-disable */
/**
 * Finance Tracker API
 * Read-only REST API that surfaces financial data collected by the CLI ingestion tool. All writes are performed exclusively by the CLI.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TransactionRead } from './transaction-read';

/**
 * Paginated wrapper returned by ``GET /api/v1/transactions``.
 */
export interface TransactionListResponse {
    'items': Array<TransactionRead>;
    'page': number;
    'page_size': number;
    'total': number;
}

